#spring.application.name=lesson
#
#my.customer.property = students
#spring.profiles.active=dev,customer

spring:
  #Connection
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/file-upload
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  #jpa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #Spring Batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 9090